フォロー機能とプロフィール機能のテスト結果＆質問
isakashiori/mokumoku pull request #1
Opened 2022-12-05 20:50 UTC by isakashiori

お疲れ様です。
課題であったフォロー機能はテスト全て通りました。
以下テスト結果です。
[![Image from Gyazo](https://i.gyazo.com/68ede7fced72a44f7219d1011a2fa632.png)](https://gyazo.com/68ede7fced72a44f7219d1011a2fa632)

しかし、プロフィール機能のテストが通らずの状態です。
以下、テスト結果です。
[![Image from Gyazo](https://i.gyazo.com/971d2c95466a581d032bdfaedba1044f.png)](https://gyazo.com/971d2c95466a581d032bdfaedba1044f)

共通してhobbyの内容が表示されていないのか`expect(page).to have_content(attended_event.user.hobby)`となります。
spec/system/profiles_spec.rb内にbyebugを入れてnextで一行づつ該当の場所まで調べてみたのですが、hobbyの値が取得できているように思えます。

少しアドバイスを頂ければ幸いです。よろしくお願いいたします。

2022-12-06 01:27 UTC, Tsuchiya2 commented
ご提出ありがとうございます。
`bundle exec rspec`コマンド実行結果の共有をお願いします。

テストコードを確認したり、エラー文、ローカルでの操作等からテストが通らない原因の調査・調査からの仮説立て・仮説に基づいて検証＆修正のサイクルを回して、`bundle exec rspec`コマンド実行した際に全ての項目がクリアする状態を目指しましょう。

2022-12-06 12:20 UTC, isakashiori commented
お疲れ様です。
ご確認ありがとうございます。
上記の件ですが、テストが通らない原因としては参加者のユーザー一覧をパーシャルファイル内でローカル変数として
定義していたため、コントローラーに参加者ユーザーの変数が送られずエラーが出ていると考えました。
そのため、パーシャルファイルを使わずに、インスタンス変数として定義してあげて該当のコントローラーに送ろうとしたのですが、下記のようなエラーが出ております。
[![Image from Gyazo](https://i.gyazo.com/217f07a329abbcabb334c8b2a6c3714a.png)](https://gyazo.com/217f07a329abbcabb334c8b2a6c3714a)
`avatar`というメソッドが定義されていないとありますが、パーシャルファイルで切り出してあげていた時はこのようなエラーが起きず、パーシャルファイルから中身を出してあげて、ローカル変数からインスタンス変数に変更したときにエラーが起きてしまいました。
https://stackoverflow.com/questions/52771022/undefined-method-exists-for-drapercollectiondecorator

またテスト結果としても、前回と同様のエラーでテストが通っていません。
パーシャル内のローカル変数をインスタンス変数化して該当のコントローラーに送る方法が見つけることができていない状態です。
できれば、パーシャルファイルを使わず、中身を出してインスタンス変数として値を送れればと思いますが、
上記エラーが出てしまい手詰まりとなっているため、ご教示いただければありがたいです。
何卒よろしくお願いいたします。
[![Image from Gyazo](https://i.gyazo.com/3defd6ef810f6d32ecff5f65a1aa522c.jpg)](https://gyazo.com/3defd6ef810f6d32ecff5f65a1aa522c)

2022-12-06 12:55 UTC, isakashiori commented
何度もすみません。
`app/views/events/_attendee.html.erb`内の以下のlink_toでクエリパラメータでprofileコントローラーに値を送って
`params[:user_id]`の形で受け取れるようにしたいのですが、
コンソールでparams[:user_id]の値を確かめるとnilになっており、profileコントローラー内のupdateアクションが思ったように動いてくれない状態です。
```
<%= link_to attendee.name, mypage_profile_path(user_id: attendee.id) %>
  
```

今思えば、パーシャル内でパラメーターの値を送っているだけなので、ローカル変数は関係ないことになるのではと
考え直しました。

2022-12-07 11:48 UTC, isakashiori commented
テスト結果のスクショ
[![Image from Gyazo](https://i.gyazo.com/4c5ea9cc571e16c8849eb58a047688a8.png)](https://gyazo.com/4c5ea9cc571e16c8849eb58a047688a8)
テスト結果
[![Image from Gyazo](https://i.gyazo.com/6f7de76d3b42b62376233fdc0a69c0cc.png)](https://gyazo.com/6f7de76d3b42b62376233fdc0a69c0cc)

テスト結果で通らない[読書]がスクショ上またprofile.specにてbyebugを仕込んでプラウザを確認しても
hobbyが表示されておりました。
検証ツールでHTMLを確認しましたが、他の欄と異なる点が見つけることができませんでした。

2022-12-08 01:52 UTC, Tsuchiya2 commented
ご提出ありがとうございます。
いくつか確認ですが、[こちら](https://github.com/isakashiori/mokumoku/pull/1#issuecomment-1340852574)にアップされているスクリーンショットですが、期待している画面と異なるように見えました。

対象のコードは以下かと思うのですが、こちらはイベント作成したユーザーとは別ユーザーでログインして、表示されているイベントから主催者の名前をクリックして、主催者の名前・Hobby・Profileが閲覧できるページへ遷移するはずなのですが、スクリーンショットはプロフィールの編集ページに遷移しているかと思うので、一旦その辺りの確認をお願いしたいです。

```ruby
context 'イベント参加者のプロフィールを閲覧できる' do
  it 'イベント詳細ページから参加者の名前をクリックすると、対象ユーザーのhobby・profileが閲覧できる。' do
    attended_event
    login(new_user)
    visit root_path
    expect(page).to have_content(attended_event.event.title)

    click_link attended_event.event.title
    click_link attended_event.user.name

    expect(page).to have_content(attended_event.user.name)
    expect(page).to have_content(attended_event.user.hobby)
    expect(page).to have_content(attended_event.user.profile)
  end
end
```

2022-12-08 10:43 UTC, isakashiori commented
@Tsuchiya2 
お疲れ様です。
指摘いただいた点を修正したところ、テストが全て通りました...!
ご確認お願いいたします。
[![Image from Gyazo](https://i.gyazo.com/3cb7ff682fe504a11a4ae679e0bf1ed5.png)](https://gyazo.com/3cb7ff682fe504a11a4ae679e0bf1ed5)

長期間ご対応いただきありがとうございます....

2022-12-08 11:09 UTC, busitora requested changes

2022-12-08 11:09 UTC, busitora commented on app/controllers/profiles_controller.rb
> +        @user = User.find(params[:id])
空白削除しましょう！

2022-12-08 11:09 UTC, busitora commented on spec/decorators/profile_decorator_spec.rb
> +
不要なSpecは消しましょう！

2022-12-08 12:27 UTC, isakashiori commented on app/controllers/profiles_controller.rb
> +        @user = User.find(params[:id])
ご指摘ありがとうございます。
修正しました。

2022-12-08 12:29 UTC, isakashiori commented on spec/decorators/profile_decorator_spec.rb
> +
require 'rails_helper'の記述を削除しました。

2022-12-08 12:34 UTC, busitora commented
LGTM！

2022-12-24 04:44 UTC, merged